### ISSUE TITLE
How do we detect that we're running pynvim in vimrc?

### ISSUE THREAD

**Issue by trusktr** [neovim/python-client#134]
What can we look for? `has('gui_running')` returns `0`.

**Comment by tarruda** [comment]
Unfortunately this is not possible because by the time vimrc is sourced the GUI isn't attached yet.

We do need a way to run GUI-specific code though, maybe a `UIAttached` autocmd?

**Comment by justinmk** [comment]
> maybe a UIAttached autocmd

:+1:  Though I would like to discuss nudging users and plugin authors towards using the API for all new Nvim features, instead of extending VimL. We would first need to settle on a design for subscribing to API events via VimL. Then we could avoid all future need to add more VimL events, and instead focus on adding API events. Similar to UI messages, except non-UI clients (including the current VimL host) should be able to publish/subscribe via the API without implementing a UI. 

I hinted at this in https://github.com/neovim/neovim/pull/2993#issuecomment-125627248 . @tarruda I believe you had plans to remove the subscribe() feature so I'm wondering what your plans are for the general ability to send/receive messages. Is it too risky? I am very interested in trying to keep most new features in the API, it really makes future compat with Neovim a non-issue and allows us the freedom to design things without working around existing Vim traditions.

**Comment by trusktr** [comment]
Could GUIs pass their name in the autocmd?

**Comment by tarruda** [comment]
> I hinted at this in neovim/neovim#2993 (comment) . @tarruda I believe you had plans to remove the subscribe() feature so I'm wondering what your plans are for the general ability to send/receive messages. Is it too risky? I am very interested in trying to keep most new features in the API, it really makes future compat with Neovim a non-issue and allows us the freedom to design things without working around existing Vim traditions.

My goal was not to completely remove `subscribe()` / `unsubscribe()`, but reimplement it in vimscript since it would be easier to maintain/modify in the future. One way would be to do something like the existing remote plugin helper functions(`remote#define#CommandOnHost` for example), another more polished alternative is to allow vimscript to register listeners for msgpack-rpc calls that are not handled by C:

```vim
function! s:Subscribe()
  ...
endfunction
function! s:Unsubscribe()
  ...
endfunction
call rpcregister(0, 'subscribe', 's:Subscribe')
call rpcregister(0, 'subscribe', 's:Unsubscribe')
```

`rpcregister` could be used to register a handler to a specific channel number or to all channels(0)

> Could GUIs pass their name in the autocmd?

Is there such thing such as "Gui name"? I suppose we could add a `v:ui_name` variable that gets set to an arbitrary string passed to `ui_attach`.

**Comment by bfredl** [comment]
Not relevant in this repo anymore (see python-gui)

**Comment by trusktr** [comment]
@bfredl Can you paste an example?
