### ISSUE TITLE
Cannot start gtk GUI

### ISSUE THREAD

**Issue by coolwanglu** [neovim/python-client#89]
When started as `python -m neovim.ui.cli -gn`, I got lots of Attribute errror, complaining `self._screen` is None. It seems that no `resize` event is not received at the beginning, (which also happened in my Atom Shell UI).

If started as `python -m neovim.ui.cli -gn -c <path>`, I got an error `TypeError: Couldn't find foreign struct converter for 'cairo.Context'`

**Comment by tarruda** [comment]
> If started as python -m neovim.ui.cli -gn -c <path>, I got an error TypeError: Couldn't find foreign struct converter for 'cairo.Context'

It seems like your'e missing cairo gobject bindings. Whats your OS/version?

**Comment by coolwanglu** [comment]
Oh it could be, let me try.
I'm using Ubuntu 14.10

**Comment by tarruda** [comment]
Try `apt-get install python-gi-cairo`

**Comment by coolwanglu** [comment]
Thanks, I've just installed and package and tried again, now a window flashes before it immediately disappeared, and the program exited without any error.

**Comment by coolwanglu** [comment]
Oh, but `python ... -gn` is able to run now.

**Comment by tarruda** [comment]
> Thanks, I've just installed and package and tried again, now a window flashes before it immediately disappeared, and the program exited without any error.

What command you tried? BTW you don't need the -n flag, its just a helper I added for attaching the screen during functional tests.

**Comment by coolwanglu** [comment]
`python -m neovim.ui.cli -gn -c <listen_path>`.
Btw, I didn't install the package, I just ran it in the root dir.

**Comment by tarruda** [comment]
> python -m neovim.ui.cli -gn -c <listen_path>.
Btw, I didn't install the package, I just ran it in the root dir

Even without installing the package there shouldn't be a problem, I just did it on my machine and it successfully connects to `<listen_path>`. Can you add some print statements to discover whats wrong?

**Comment by coolwanglu** [comment]
OK I'll try. It could be some missing packages also, as I didn't install the meta ubuntu package.

**Comment by tarruda** [comment]
> python -m neovim.ui.cli -gn -c .
Btw, I didn't install the package, I just ran it in the root dir

Hmm now that I think about it, this shouldn't work on master because the abstract ui termcap isn't used by default(I've been using the neovim/neovim#1820 branch for some time now). If you start a normal nvim instance it will use the old terminal UI/termcap.

Try this though:

- In one shell, enter `python -m neovim.ui.cli -g -l /tmp/nvim` (start a new instance with abstract ui listening on /tmp/nvim)
- From another shell, enter `python -m neovim.ui.cli -g -c /tmp/nvim` (connect to the previous instance)

**Comment by coolwanglu** [comment]
It's working now! Thanks!
