### ISSUE TITLE
pynvim does not have 'guifont' option

### ISSUE THREAD

**Issue by sirex** [neovim/python-client#93]
There is no `set guifont=*` option, that is available in `gvim` to configure font family and font size.

**Comment by tarruda** [comment]
I plan to add a command for selecting the font when the pynvim gui is ported to C

**Comment by sirex** [comment]
For me it was quite confusing to understand, that `python-client` is not only a library for writing neovim plugins, but it is also a GTK GUI.

I'd like to contribute to `pynvim` as neovim GTK GUI, for example by adding `'guifont'` option, since I know python, but I'm not sure what is the status of `python-client` as a GTK GUI, since you mentioned, that there are plans to port it to C. As I understand, plans are to leave `python-client` just as a plugin library and move all GUI related things to separate neovim GUI project written in C?

**Comment by tarruda** [comment]
> For me it was quite confusing to understand, that python-client is not only a library for writing neovim plugins, but it is also a GTK GUI.

I know, it was lazy of me to put everything into the same project. The python-client will eventually be split into three projects:

- client library
- plugin host
- pynvim

> I'd like to contribute to pynvim as neovim GTK GUI, for example by adding 'guifont' option, since I know python, but I'm not sure what is the status of python-client as a GTK GUI, since you mentioned, that there are plans to port it to C. As I understand, plans are to leave python-client just as a plugin library and move all GUI related things to separate neovim GUI project written in C?

What I want to do is extract the bulk of the pynvim GUI logic into a Gtk widget written in C. After that pynvim will be reimplemented on top of the widget, because it is much faster to handle screen updates in C. I have optimized pynvim a lot, but it still lags when the screen dimensions are too great(or the font is small).

As for adding font customization to pynvim, I was thinking of adding an ex command when it attaches to nvim. This command will use a completion function also implemented by pynvim(for details on how to do that, you need to get familiar with [remote plugins](http://neovim.org/doc/user/remote_plugin.html#remote-plugin))

If you want to implement that, feel free to do it because the code wont be part of the gtk widget. The msgpack-rpc part of pynvim is still going to be python.

**Comment by dani-h** [comment]
@tarruda Is there any ETA on when a nvim gui will be released? I use Neovim in the terminal but since there are a bunch of keys missing (i.e Ctrl + tab) I end up using gvim.

**Comment by sirex** [comment]
@dani-h for the font, not very convenient, but you can change it here: https://github.com/neovim/python-client/blob/master/neovim/ui/gtk_ui.py#L70

**Comment by dani-h** [comment]
@sirex Thanks. I grepped for that option and found it, but figured if the font can't be changed there has to be other trivial stuff missing as well.

**Comment by tarruda** [comment]
> @tarruda Is there any ETA on when a nvim gui will be released?

Not yet, sorry. I'm currently using my time to fix job control and `:terminal` bugs which are a bit more urgent.

**Comment by vhakulinen** [comment]
> What I want to do is extract the bulk of the pynvim GUI logic into a Gtk widget written in C.

@tarruda so you are going to do Gtk widget for use with neovim? Any work being done on that?

**Comment by tarruda** [comment]
@vhakulinen I have not began yet, but there's a good chance it will happen in the next month

**Comment by bfredl** [comment]
If someone works on this please send PR to `neovim/python-gui`
